### ISSUE TITLE
Issue with Basic-Tasmota communicating with smartthings`

### ISSUE THREAD

**Issue by jlovenduski** [mhutchy/Sonoff---Tasmota#1]
I'm relatively new to this but I've tried every firmware / device handler / smart app code I could find on this subject.

Old - new I can't seem to get anything to work  with a sonoff basic flashed the with new tasmota to function via smartthings classic. Seems the most logical at this point. I'd like to use everything from one location I'm a few days deep in this off and on trying new things. Any suggestions?

Ive tried ercom123's firmware / handler/ smartapp. Doesnt find anything and you cant manually add.
Ive tried some of the older handlers and yours as well with the same results when adding a device via IDE it says its there and active but nothing responds, no information or feedback. 

Any help would be appreciated. Thanks

**Comment by mhutchy** [comment]
Hi, It should be relatively easy up at up once you have tasmota installed on the sonoff. When 1st installed the sonoff acts as a WiFi access point. You need to connect your pc to it and then configure it to use your WiFi by adding the ssid and password of your home WiFi access point. Once that is done it will reboot and obtain an op address from your home WiFi access point. You will then need to look into your dhcp server to see what address it has been given and program your dhcp to give the sonic wall a fixed ip. Once you know the ip of the sonic wall you can check all is ok by browsing its address on your pc. To add to smartthings, select add device in the web interface and put the same op address as the device network Id. It sold then be active in smartthings. RegardsMarkSent from my phoneEnvoyé depuis mon téléphone 
-------- Original message --------From: jlovenduski <notifications@github.com> Date: 02/03/2019  23:53  (GMT+01:00) To: mhutchy/Sonoff---Tasmota <Sonoff---Tasmota@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [mhutchy/Sonoff---Tasmota] Issue with Basic-Tasmota communicating
  with smartthings` (#1) I'm relatively new to this but I've tried every firmware / device handler / smart app code I could find on this subject.
Old - new I can't seem to get anything to work  with a sonoff basic flashed the with new tasmota to function via smartthings classic. Seems the most logical at this point. I'd like to use everything from one location I'm a few days deep in this off and on trying new things. Any suggestions?
Ive tried ercom123's firmware / handler/ smartapp. Doesnt find anything and you cant manually add.
Ive tried some of the older handlers and yours as well with the same results when adding a device via IDE it says its there and active but nothing responds, no information or feedback.
Any help would be appreciated. Thanks

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhutchy/Sonoff---Tasmota","title":"mhutchy/Sonoff---Tasmota","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhutchy/Sonoff---Tasmota"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Issue with Basic-Tasmota communicating with smartthings` (#1)"}],"action":{"name":"View Issue","url":"https://github.com/mhutchy/Sonoff---Tasmota/issues/1"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhutchy/Sonoff---Tasmota/issues/1",
"url": "https://github.com/mhutchy/Sonoff---Tasmota/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jlovenduski** [comment]
I thought the same thing and I think that's why im lost on this. Here is the odd part. All of that works correctly up until I get to smartthings. Tasmota flashes fine no issues there. Adding it my network, hitting the web interface of the device. Confirming that it functions, etc. I've processed different firmwares from the interface as well. Everything on the Sonoff/tasmota side works great.

when I manually add a device by IP to my list in IDE and give it the device handler you created It says its active from the IDE interface but from the Smartthings classic app. I can't interact with the device at all. If I try erocm123s handler, app, and firmware. It doesn't discover anything either.

From a network standpoint, nothing is restricted internal. I can access the device via its IP/ web interface without any issue. 

I thought this would work, at the very least locally, without a smartthings hub but I'm starting to get the feeling that's what I'm missing. :) I guess the first question should have been do I require a smartthings hub to pull this off.

**Comment by mhutchy** [comment]
Hi, Yes you need the smartthings hub as the tcpip instructions to the sonoff are issued via a hub command. Looks like you need to go shopping. You should still be able to connect directly to the sonoff with your pc phone etc as long as it is on the same lan but you won't be able to integrate it into smartthings. Regards Mark Sent from my phoneEnvoyé depuis mon téléphone 
-------- Original message --------From: jlovenduski <notifications@github.com> Date: 04/03/2019  15:21  (GMT+01:00) To: mhutchy/Sonoff---Tasmota <Sonoff---Tasmota@noreply.github.com> Cc: mhutchy <mark@hutchy.eu>, Comment <comment@noreply.github.com> Subject: Re: [mhutchy/Sonoff---Tasmota] Issue with Basic-Tasmota communicating
  with smartthings` (#1) I thought the same thing and I think that's why im lost on this. Here is the odd part. All of that works correctly up until I get to smartthings. Tasmota flashes fine no issues there. Adding it my network, hitting the web interface of the device. Confirming that it functions, etc. I've processed different firmwares from the interface as well. Everything on the Sonoff/tasmota side works great.
when I manually add a device by IP to my list in IDE and give it the device handler you created It says its active from the IDE interface but from the Smartthings classic app. I can't interact with the device at all. If I try erocm123s handler, app, and firmware. It doesn't discover anything either.
From a network standpoint, nothing is restricted internal. I can access the device via its IP/ web interface without any issue.
I thought this would work, at the very least locally, without a smartthings hub but I'm starting to get the feeling that's what I'm missing. :) I guess the first question should have been do I require a smartthings hub to pull this off.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mhutchy/Sonoff---Tasmota","title":"mhutchy/Sonoff---Tasmota","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/mhutchy/Sonoff---Tasmota"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jlovenduski in #1: I thought the same thing and I think that's why im lost on this. Here is the odd part. All of that works correctly up until I get to smartthings. Tasmota flashes fine no issues there. Adding it my network, hitting the web interface of the device. Confirming that it functions, etc. I've processed different firmwares from the interface as well. Everything on the Sonoff/tasmota side works great.\r\n\r\nwhen I manually add a device by IP to my list in IDE and give it the device handler you created It says its active from the IDE interface but from the Smartthings classic app. I can't interact with the device at all. If I try erocm123s handler, app, and firmware. It doesn't discover anything either.\r\n\r\nFrom a network standpoint, nothing is restricted internal. I can access the device via its IP/ web interface without any issue. \r\n\r\nI thought this would work, at the very least locally, without a smartthings hub but I'm starting to get the feeling that's what I'm missing. :) I guess the first question should have been do I require a smartthings hub to pull this off. \r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mhutchy/Sonoff---Tasmota/issues/1#issuecomment-469269481"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/mhutchy/Sonoff---Tasmota/issues/1#issuecomment-469269481",
"url": "https://github.com/mhutchy/Sonoff---Tasmota/issues/1#issuecomment-469269481",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jlovenduski** [comment]
LOL yes, I do. That was my fault. Just ordered one. Smart things integration is what I was looking for. Really just trying to find a useful interface that can include everything and provide good feedback.  Looks like smart things classing is the way to go. Google home looks a bit to drawn out now and Yeti needs a lot of work. I did start looking at Domoticz as well.

 It's one of those frustrations "I don't care what brand the item is I just want to keep it under one platform instead of 20"

I'll let you know how I make out. Thanks again for your help.
